apiVersion: v1
kind: Secret
metadata:
  name: it-services-portal-secret
  env: uat
type: Opaque
data:
  # Base64 encoded values for environment variables
  DB_HOST: aXRzLXNlcnZpY2VzLWFwbC
  DB_PORT: NTQzMg==
  DB_NAME: aXRzLXNlcnZpY2VzLWRi
  DB_USER: aXRzLXNlcnZpY2VzLXVzZXI=
  DB_PASSWORD: aXRzLXNlcnZpY2VzLXBhc3N3b3Jk