kind: Service
apiVersion: v1
metadata:
  name: it-services-portal-svc
spec:
  type: NodePort
  selector:
    app: it-services-portal
    env: uat
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002