environment: uat
app: it-services-portal

image:
  repository: lerndevops/it-services-portal
  tag: latest
  pullPolicy: IfNotPresent

replicas: 2

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "20m"
    memory: "64Mi"

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30002

deployment:
  containerPort: 8080
  
config:
  APP_ENV: "uat"
  APP_DEBUG: "false"
  APP_PORT: "8080"

secrets:
  DB_HOST: "aXRzLXNlcnZpY2VzLWFwbA=="
  DB_PORT: "NTQzMg=="
  DB_NAME: "aXRzLXNlcnZpY2VzLWRi"
  DB_USER: "aXRzLXNlcnZpY2VzLXVzZXI="
  DB_PASSWORD: "aXRzLXNlcnZpY2VzLXBhc3N3b3Jk"
