apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-services-portal
  labels:
    env: uat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        env: uat
    spec:
      containers:
      - name: it-services-portal
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
