apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
  - ../../base

commonLabels:
  env: uat

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - configmap-patch.yaml
  - secret-patch.yaml
