apiVersion: v1
kind: Secret
metadata:
  name: it-services-portal-secret
type: Opaque
data:
  DB_HOST: aXRzLXNlcnZpY2VzLWFwbA==
  DB_PORT: NTQzMg==
  DB_NAME: aXRzLXNlcnZpY2VzLWRi
  DB_USER: aXRzLXNlcnZpY2VzLXVzZXI=
  DB_PASSWORD: aXRzLXNlcnZpY2VzLXBhc3N3b3Jk
