apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-secret
  labels:
    env: {{ .Values.environment }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
{{- end }}
