kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
    env: {{ .Values.environment }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
