apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: it-services-portal-dev
  namespace: dev

bases:
  - ../../base

commonLabels:
  env: dev

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - configmap-patch.yaml
